alphaBudget/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

alphaBudget/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alphaBudget/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

alphaBudget/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def new
    end

    def create
    end
end

alphaBudget/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

alphaBudget/app/helpers/application_helper.rb
module ApplicationHelper
end

alphaBudget/app/helpers/transactions_helper.rb
module TransactionsHelper
end

alphaBudget/app/helpers/welcome_helper.rb
module WelcomeHelper
end

alphaBudget/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBudget</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

alphaBudget/app/views/transactions/new.html.erb
<%= form_for :transaction, url: transactions_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

alphaBudget/app/views/welcome/index.html.erb
<h1>Welcome to the budget app</h1>
<p>Project alpha</p>